collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#0D0D0E'
    - '#DFCFBD'
    - '#FB75BE'
    - '#ADA288'
    - '#C64C7E'
  rhythmicContrast: 1
typography_spectrum: 0.5171858
layout_spectrum: 0.2301855
name: Aldobot
