layout_spectrum: 0.3367347
color:
  saturation: 1
  lightness: 0
  brandStrength: 1
  brandColors:
    - '#0B0C0E'
    - '#01667F'
    - '#FF4EE7'
    - '#92D8E0'
    - '#01F593'
  rhythmicContrast: 1
typography_spectrum: 0.5171858
name: Aldobot
